# Generated by Django 3.2.20 on 2023-08-14 09:31

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('running', 'Running'), ('full body', 'Full Body'), ('upper body', 'Upper Body'), ('lower body', 'Lower Body'), ('mobility', 'Mobility')], default='full body', max_length=50)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
                ('completed', models.ManyToManyField(blank=True, related_name='workout_completed', to=settings.AUTH_USER_MODEL)),
                ('exercise1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise1', to='planner.exercise')),
                ('exercise10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise10', to='planner.exercise')),
                ('exercise2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise2', to='planner.exercise')),
                ('exercise3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise3', to='planner.exercise')),
                ('exercise4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise4', to='planner.exercise')),
                ('exercise5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise5', to='planner.exercise')),
                ('exercise6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise6', to='planner.exercise')),
                ('exercise7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise7', to='planner.exercise')),
                ('exercise8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise8', to='planner.exercise')),
                ('exercise9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise9', to='planner.exercise')),
                ('saves', models.ManyToManyField(blank=True, related_name='workout_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'admin'), (1, 'standard')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workout', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workout', to='planner.workout')),
            ],
            options={
                'ordering': ['-saved_on'],
            },
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_workout', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_workout', to='planner.workout')),
            ],
            options={
                'ordering': ['-completed_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planner.workout')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
