# Generated by Django 3.2.20 on 2023-08-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercise10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise10', to='planner.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise4', to='planner.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise5', to='planner.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise6', to='planner.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise7', to='planner.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise8', to='planner.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise9', to='planner.exercise'),
        ),
    ]
