# Generated by Django 3.2.20 on 2023-08-15 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20230815_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('running', 'Running'), ('full body', 'Full Body'), ('upper body', 'Upper Body'), ('lower body', 'Lower Body'), ('mobility', 'Mobility')], default='full body', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise10_reps',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise10_sets',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise1_reps',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise1_sets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise2_reps',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise2_sets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise3_reps',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise3_sets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise4_reps',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise4_sets',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise5_reps',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise5_sets',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise6_reps',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise6_sets',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise7_reps',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise7_sets',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise8_reps',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise8_sets',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise9_reps',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise9_sets',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
