# Generated by Django 3.2.20 on 2023-08-15 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20230815_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('running', 'Running'), ('full body', 'Full Body'), ('upper body', 'Upper Body'), ('lower body', 'Lower Body'), ('mobility', 'Mobility')], max_length=10, null=True), null=True, size=None),
        ),
    ]
