# Generated by Django 3.2.20 on 2023-08-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20230815_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.category'),
        ),
    ]
