# Generated by Django 3.2.20 on 2023-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default', max_length=200, unique=False),
        ),
    ]
