# Generated by Django 3.2.20 on 2023-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
