# Generated by Django 3.2.20 on 2023-08-19 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise1',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise10',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise10_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise10_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise1_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise1_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise2',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise2_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise2_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise3',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise3_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise3_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise4',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise4_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise4_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise5',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise5_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise5_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise6',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise6_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise6_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise7',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise7_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise7_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise8',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise8_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise8_sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise9',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise9_reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise9_sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='planner.workout'),
        ),
    ]
