# Generated by Django 3.2.20 on 2023-08-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_exercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
