# Generated by Django 3.2.20 on 2023-08-26 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_auto_20230825_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.RemoveField(
            model_name='save',
            name='workout',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='planner.workout'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Complete',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
