# Generated by Django 3.2.20 on 2023-08-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
